#!/usr/bin/env python3
"""
validate_full_canonical_csv.py
================================
Validates a CSV file against full_canonical__lgbm/feature_order.json.

Usage:
    python tools/validate_full_canonical_csv.py --csv captures/live_generated_full_canonical_test.csv

Typical dry-run workflow:
    # 1. Generate features from a PCAP:
    python tools/pcap_to_live_stream.py --dry-run ^
        --pcap captures/vm_basic_benign.pcap ^
        --out-csv captures/live_generated_full_canonical_test.csv

    # 2. Validate the output:
    python tools/validate_full_canonical_csv.py ^
        --csv captures/live_generated_full_canonical_test.csv

IMPORTANT:
    Do NOT pass demo_flows_full_canonical.csv as the --csv argument.
    That file is a reference schema, not live-generated output.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import List, Tuple

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[union-attr]
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[union-attr]
except Exception:
    pass

try:
    import pandas as pd
except ImportError:
    print("[ERROR] Missing dependency: pandas. Install: pip install pandas")
    sys.exit(1)

_THIS_FILE   = Path(__file__).resolve()
PROJECT_ROOT = _THIS_FILE.parent.parent
BUNDLE_ROOT  = PROJECT_ROOT / "backend" / "runtime_bundle" / "app_runtime_bundle"
FEATURE_ORDER_PATH = BUNDLE_ROOT / "runtime_models" / "full_canonical__lgbm" / "feature_order.json"

META_COLS = {"session_id", "flow_id", "capture_id", "dataset", "label",
             "timestamp", "src_ip", "dst_ip", "protocol", "dst_port", "scenario"}

DEMO_REF_CSV_NAME = "demo_flows_full_canonical.csv"


def _load_feature_order() -> List[str]:
    if not FEATURE_ORDER_PATH.exists():
        print(f"[ERROR] feature_order.json not found: {FEATURE_ORDER_PATH}")
        sys.exit(1)
    with FEATURE_ORDER_PATH.open("r", encoding="utf-8") as fh:
        return json.load(fh)["feature_order"]


def validate_csv(csv_path: Path, feature_order: List[str]) -> Tuple[bool, List[str]]:
    """Validate a CSV against full_canonical feature_order. Returns (passed, messages)."""
    messages: List[str] = []

    if DEMO_REF_CSV_NAME in csv_path.name:
        messages.append(
            f"WARNING: '{csv_path.name}' looks like the reference demo CSV, "
            "not a live-generated PCAP output. "
            "Pass a CSV generated by pcap_to_live_stream.py instead."
        )

    df = pd.read_csv(csv_path)
    n_rows, n_cols = df.shape

    messages.append(f"CSV             : {csv_path.resolve()}")
    messages.append(f"Rows / Columns  : {n_rows} / {n_cols}")

    if n_rows == 0:
        messages.append("ERROR: CSV has 0 rows.")
        return False, messages

    columns = list(df.columns)
    model_cols = [c for c in columns if c not in META_COLS]
    meta_cols  = [c for c in columns if c in META_COLS]

    missing = [f for f in feature_order if f not in df.columns]
    extra   = [c for c in model_cols if c not in set(feature_order)]

    messages.append(f"Required features: {len(feature_order)}")
    messages.append(f"Present features : {len(feature_order) - len(missing)}")
    messages.append(f"Missing features : {len(missing)}")
    if missing:
        messages.append(f"  Missing: {missing}")
    messages.append(f"Extra columns    : {len(extra)}  {extra if extra else ''}")
    messages.append(f"Metadata columns : {meta_cols}")

    if missing:
        messages.append(
            f"\nFAILED: Live PCAP features are not valid for full_canonical__lgbm. "
            f"Missing features: {missing}"
        )
        return False, messages

    # Numeric validity
    nan_total = 0
    inf_total = 0
    problem_cols: List[str] = []
    for feat in feature_order:
        col = pd.to_numeric(df[feat], errors="coerce")
        nc = int(col.isna().sum())
        ic = int((col.abs() == float("inf")).sum())
        nan_total += nc
        inf_total += ic
        if nc > 0 or ic > 0:
            problem_cols.append(f"{feat}(NaN={nc},Inf={ic})")

    messages.append(f"NaN in features  : {nan_total}")
    messages.append(f"Inf in features  : {inf_total}")
    if problem_cols:
        messages.append(f"Problem features : {problem_cols}")

    # Dry-run: enforce feature order
    try:
        X = df.loc[:, feature_order].to_numpy(dtype=float)
        messages.append(f"Feature matrix   : shape={X.shape}")
        messages.append(f"Order enforced   : df.loc[:, feature_order] — YES")
    except Exception as exc:
        messages.append(f"ERROR in feature matrix: {exc}")
        return False, messages

    # Preview
    messages.append(f"\nFirst 3 rows (model features, rounded to 4 dp):")
    for i, row in df[feature_order].head(3).iterrows():
        messages.append(f"  row {i}: {dict(row.round(4))}")

    passed = (len(missing) == 0 and nan_total == 0 and inf_total == 0)
    if passed:
        messages.append(
            f"\nPASSED — valid for full_canonical__lgbm\n"
            f"  model_id       = full_canonical__lgbm\n"
            f"  feature_schema = full_canonical_34\n"
            f"  rows_ingested  = {n_rows}"
        )
    else:
        issues = []
        if nan_total:
            issues.append(f"{nan_total} NaN")
        if inf_total:
            issues.append(f"{inf_total} Inf")
        messages.append(f"\nFAILED: {'; '.join(issues)}")

    return passed, messages


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Validate a live-generated PCAP feature CSV against "
            "full_canonical__lgbm/feature_order.json.\n\n"
            "Do NOT pass demo_flows_full_canonical.csv (reference schema only).\n"
            "Use a CSV from: python tools/pcap_to_live_stream.py --dry-run --out-csv ..."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--csv", required=True, metavar="PATH",
                        help="Path to the live-generated feature CSV to validate.")
    args = parser.parse_args()

    csv_path = Path(args.csv)
    if not csv_path.is_absolute():
        csv_path = PROJECT_ROOT / csv_path
    if not csv_path.exists():
        print(f"[ERROR] CSV not found: {csv_path}")
        sys.exit(1)

    feature_order = _load_feature_order()
    print(f"[*] Loaded feature_order.json: {len(feature_order)} features")
    print(f"[*] Model: full_canonical__lgbm\n")

    passed, messages = validate_csv(csv_path, feature_order)
    for msg in messages:
        print(msg)

    sys.exit(0 if passed else 1)


if __name__ == "__main__":
    main()

